# Generated by Django 3.2.7 on 2021-09-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveBigIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('quality', models.CharField(choices=[('good', 'good'), ('average', 'average'), ('bad', 'bad')], max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
