# Generated by Django 3.2.7 on 2021-09-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.CharField(choices=[('brand_new', 'brand_new'), ('good', 'good'), ('average', 'average'), ('bad', 'bad')], max_length=250),
        ),
    ]
