# Generated by Django 3.2.7 on 2021-09-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=250)),
                ('brand_logo', models.ImageField(upload_to='')),
                ('brand_description', models.TimeField()),
                ('brand_moto', models.SlugField()),
            ],
            options={
                'ordering': ['brand_name'],
            },
        ),
    ]
