# Generated by Django 3.2.7 on 2021-09-21 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_person_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_cast', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=250)),
                ('belongs_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.parents')),
            ],
        ),
    ]
