# Generated by Django 3.2.7 on 2021-09-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_item_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_belongs_to',
            field=models.ManyToManyField(to='myapp.Item'),
        ),
    ]
